### ISSUE TITLE
热度排序算法改进，随时间衰减

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaBackendCenter#101]
或许可以加个随时间衰减的系数，不然排在最前面的一直是结束了很久的活动关

**Comment by MistEO** [comment]
之前好像还有群友说，可以按近 7 天的 浏览/点赞率 来，这样不但可以把过时的活动关降下来，还可以在平时提高主线关卡的排名

**Comment by dragove** [comment]
已经上线第一个版本，后续更新到[#105](https://github.com/MaaAssistantArknights/MaaBackendCenter/issues/105)讨论
