### ISSUE TITLE
建议热度选项卡根据关卡是否开放推荐

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaBackendCenter#105]
落叶逐火 一直霸榜（

**Comment by dragove** [comment]
https://github.com/MaaAssistantArknights/MaaBackendCenter/issues/101 会先上线，看看效果。目前后端爬取的关卡数据里没有是否开放的信息，如果效果不好再想想别的办法

**Comment by dragove** [comment]
第一个正经点的热度算啊已经上线，效果尚可，但是会存在以下问题：
1. 如该issue所说，已经关闭的关卡仍然会出现在首页，因为算法是根据过去的周数衰减，那么时间上小于一周的数据会和新关卡有同样的高分，只经过一周的数据如果访问量和一周内点赞数较多，也可能热度值较高。
2. 关卡复刻时旧作业没有加成，很难出现到首页中。
可能的解决方案：
1. 如果关卡数据中有当前是否开放的信息，可以使用该内容直接把关闭的关卡打入地狱。
2. 给近期点赞数更多权重，这样当前开放的关卡只要有用户点赞就更容易出现到首页，但是仍然存在同一周的已关闭关卡的问题，关于浏览数，目前的数据结构下没法获取近一周的浏览量，所以浏览量指标很难用。

**Comment by dragove** [comment]
当前热度凑合能用（已经考虑关卡不在开放期间之类的问题），关闭过时issue
