### ISSUE TITLE
作业站增加评论字数&删除评论的建议

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaBackendCenter#106]
rt，有时想在评论区里加上表格
但用markdown写，150个字根本不够

建议加点字数，或开个后门（）![例子.jpg](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/92996760/7154b8b4-d999-4932-ad34-0a62a512c45e)

——————————

删除评论后会留下*（已删除）*的字样
在一些讨论的评论中删评后会出现一大堆这种提示，导致后面的人很难查看（获取评论信息）

感觉这个功能很鸡肋，能不能加个让发这条消息的人能够删除提示

或让作业作者删除也行

**Comment by guansss** [comment]
显示已删除主要是为了防止引用丢失，比如 B 回复了 A，然后 A 被删除了，用户看见 B 却找不到 A 会很困惑

**Comment by yc080713** [comment]
> 显示已删除主要是为了防止引用丢失，比如 B 回复了 A，然后 A 被删除了，用户看见 B 却找不到 A 会很困惑

喔！
可是看起来真的很难受，有可能给这一块加个标识吗
比如颜色比周围正常评论深/浅一点（不懂ui，瞎说）

**Comment by guansss** [comment]
这不是已经变浅了吗（
不过应该可以压缩进一行，就像 Reddit 那样

**Comment by LuoRenMu** [comment]
我觉得字数可以扩 只不过太长了就需要前端折叠一下

**Comment by yc080713** [comment]
催一下这个问题

现在危机合约要点的词条很多，多数作业制作者又不会截合约tag图片发出来

往往要自己点进b站视频看tag感觉很麻烦

增加输入字符 可以将b站视频直接导入评论区

**Comment by dragove** [comment]
已添加功能：作者评论时字数上限限制为500字
