### ISSUE TITLE
请求在作业收到评论时的通知邮件内添加更多信息

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaBackendCenter#114]
1. 希望能在邮件的标题添加类似评论人、作业名称的信息，方便使用邮件系统对指定评论人进行屏蔽。
2. 希望能增大作业名折叠的长度限制，经常不知道是哪个作业被评论了

![Screenshot_2023-07-22-18-15-37-325-edit_com.tencent.mobileqq.jpg](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/102887808/b5e80ba8-12fc-414a-9fcb-cb5d16cfb5ea)

**Comment by LuoRenMu** [comment]
已在 31908968270f07f6816297ea66f177351626dba7 进行优化 邮件标题添加了评论人及作业名称的信息 长度限制在25
