### ISSUE TITLE
找回密码功能坏了

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/MaaBackendCenter#119]
接口/user/password/reset前后端使用的参数字段不一致导致找回密码功能失效
![图片](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/18378664/8f38e451-ce4b-41c8-be18-29c9e37aaa8c)

![图片](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/18378664/71e2dc8b-8ebb-4ce2-a597-f99ef6b3a248)

![图片](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/18378664/c83825ba-7621-4c9b-889f-4badbc992d00)

**Comment by LuoRenMu** [comment]
让前端改 (bushi

**Comment by dragove** [comment]
前端改掉了，我就先把这个关了 https://github.com/MaaAssistantArknights/maa-copilot-frontend/commit/08e8eaa5a0dc922ac52b6328d763dc2102f343ee
