### ISSUE TITLE
引航者试炼作业上传失败

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/MaaBackendCenter#126]
作者反馈前端格式校验通过，但无法上传
问题疑似出现在MoveCamera操作
![6ed79bef773d27253485a5a2f5e4c66a](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/18378664/3ac4c75c-ffc6-4e78-bf29-5dbc44cfb89a)

![35a30a02be93b44f12b1d6fd55b2ea30](https://github.com/MaaAssistantArknights/MaaBackendCenter/assets/18378664/69547e41-94a6-4b84-aab0-55b86eb52dc8)

以下为完整作业内容

{
  "minimum_required": "v4.0.0",
  "stage_name": "act3bossrush_01",
  "actions": [
    {
      "type": "SpeedUp"
    },
    {
      "type": "Deploy",
      "name": "棘刺",
      "location": [
        8,
        3
      ],
      "direction": "Down"
    },
    {
      "type": "Deploy",
      "name": "塞雷娅",
      "location": [
        8,
        4
      ],
      "direction": "Down"
    },
    {
      "type": "Deploy",
      "name": "特制水上平台",
      "location": [
        4,
        4
      ],
      "direction": "None"
    },
    {
      "type": "Deploy",
      "name": "史尔特尔",
      "location": [
        4,
        4
      ],
      "direction": "Left"
    },
    {
      "type": "Skill",
      "name": "史尔特尔",
      "kills": 5
    },
    {
      "type": "Deploy",
      "name": "蜜莓",
      "location": [
        9,
        5
      ],
      "direction": "Up"
    },
    {
      "type": "Deploy",
      "name": "特制水上平台",
      "location": [
        7,
        3
      ],
      "direction": "None"
    },
    {
      "type": "Deploy",
      "name": "星熊",
      "location": [
        7,
        3
      ],
      "direction": "Left"
    },
    {
      "type": "Deploy",
      "name": "艾雅法拉",
      "location": [
        9,
        3
      ],
      "direction": "Left"
    },
    {
      "type": "MoveCamera",
      "distance": [
        4.5,
        0
      ],
      "kills": 23
    },
    {
      "type": "Deploy",
      "name": "史尔特尔",
      "location": [
        14,
        5
      ],
      "direction": "Up"
    },
    {
      "type": "SpeedUp"
    },
    {
      "type": "Skill",
      "name": "史尔特尔",
      "pre_delay": 2500
    }
  ],
  "doc": {
    "title": "TN-1初始试炼",
    "details": "化学老施的\n遏制单元选第一个"
  },
  "groups": [],
  "opers": [
    {
      "name": "塞雷娅",
      "skill": 1,
      "skill_usage": 0
    },
    {
      "name": "棘刺",
      "skill": 3,
      "skill_usage": 1
    },
    {
      "name": "星熊",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "史尔特尔",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "蜜莓",
      "skill": 1,
      "skill_usage": 0
    },
    {
      "name": "艾雅法拉",
      "skill": 2,
      "skill_usage": 0
    }
  ]
}

**Comment by dragove** [comment]
修复版本已上线
