### ISSUE TITLE
查询作业详情时包含 uploader_id

### ISSUE THREAD

**Issue by guansss** [MaaAssistantArknights/MaaBackendCenter#160]
目前 `/copilot/get/<id>` 返回的数据中只包含 `uploader`，也就是作者的用户名

前端在判断是否显示管理按钮和评论置顶按钮时，需要检查当前用户是否为作业作者，目前的方法是比较用户名，然而用户名是允许重名的，所以和作业作者重名的用户都会显示这两个按钮（当然发送请求后还是会提示没有权限）

如果在作业详情里包含 `uploader_id` 的话就不会误判了

Edit: `uploaderId` -> `uploader_id`

**Comment by dragove** [comment]
最新版本已添加该字段
