### ISSUE TITLE
优化作业评分机制

### ISSUE THREAD

**Issue by FujiiAkane** [MaaAssistantArknights/MaaBackendCenter#82]
以前的作业站在作业评分人数过少时不予显示评分

现在的作业站是实时更新分数，没人评分是差评如潮，一人好评就是5分，两人好评差评掺半就是2.5星

可否恢复之前的“评价人数过少时不显示评分，并提示评价人数过少尚无评分”机制？

**Comment by LuoRenMu** [comment]
是的 这个问题我觉得应该移交给前端

**Comment by FujiiAkane** [comment]
> 是的 这个问题我觉得应该移交给前端

噢，那我再去前端提一下？

**Comment by guansss** [comment]
已解决，但我没有这里的权限，谁close一下（
