### ISSUE TITLE
更改作业发布网站的用户名后,无法管理更名前发布的作业

### ISSUE THREAD

**Issue by hifuclub** [MaaAssistantArknights/MaaBackendCenter#84]
更改作业发布网站的用户名后,无法管理更名前发布的作业,
修改用户名之前发布的作业的名字也还是未修改前的

**Comment by hifuclub** [comment]
![image](https://user-images.githubusercontent.com/47740858/223403844-618d1c2d-c78b-4d86-930d-6a0a1a873489.png)
![image](https://user-images.githubusercontent.com/47740858/223403922-1e3efdf3-8628-4f8f-8957-f09835d81f8d.png)

**Comment by LuoRenMu** [comment]
re [78ce743](https://github.com/MaaAssistantArknights/MaaBackendCenter/pull/83/commits/78ce743511aaa48d230d4116c8cfe5fd26238d89) #83

**Comment by Handiwork** [comment]
问题解决了吗

**Comment by LuoRenMu** [comment]
解决了 就等上线了

**Comment by dragove** [comment]
修复功能已经上线
