### ISSUE TITLE
缺少注册邮箱确认邮件

### ISSUE THREAD

**Issue by UniMars** [MaaAssistantArknights/MaaBackendCenter#98]
注册之后没有收到邮箱确认邮件，用的是qq邮箱

**Comment by GalvinGao** [comment]
现在发信商是谁的哦 @LuoRenMu

**Comment by UniMars** [comment]
> 现在发信商是谁的哦

就是我用两个qq邮箱注册，都是直接就注册成功了，中间没有邮件确认的那一步

**Comment by Handiwork** [comment]
#95 依靠 bug 运行.jpg

**Comment by Lixuhuilll** [comment]
> 现在发信商是谁的哦

和发信商没关系，因为根本就没发

**Comment by Lixuhuilll** [comment]
笑死，代码里三个发激活验证码的接口，全都要前端自行调用才发送，没一个被调用的

**Comment by Lixuhuilll** [comment]
等会我改一下，明明代码里有法激活邮件的方法，直接注册就立即发激活邮件就行了
